### ISSUE TITLE
Can't specify path to both Python2 and Python3 using cmake

### ISSUE THREAD

**Issue by swiftcoder** [verse/verse-javascript-viewer#5]
Not a big deal, but if you have both python2 and python3 installed, CMake only seems to allow you to provide the path to one of these (via defining the PYTHON_LIBRARY variable). Meaning that you can't build both the python 2 module and the python 3 module at the same time.

**Comment by swiftcoder** [comment]
Sorry, added this issue to the wrong repo.

**Comment by jirihnidek** [comment]
Hi,
I can build both binary modules (for Python2 as well for Python3) at Linux. If you have some troubles at other platform, then let me know here: https://github.com/verse/verse.
